//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno()
        {
            this.connectAll = new HashSet<connectAll>();
        }
    
        public int alumnoId { get; set; }
        public string nombre_a { get; set; }
        public string apellido_a { get; set; }
        public string dni_a { get; set; }
        public string telefono_a { get; set; }
        public Nullable<System.DateTime> fechaNacimiento_a { get; set; }
        public Nullable<int> edad_a { get; set; }
        public string direccion_a { get; set; }
        public string pais_a { get; set; }
        public string provincia_a { get; set; }
        public string localidad_a { get; set; }
        public string genero_a { get; set; }
        public Nullable<double> promedio_a { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connectAll> connectAll { get; set; }

        public alumno(int alumnoId, string nombre, string apellido, string dni, string telefono, string pais, string provincia, string localidad,
    int edad, string genero, DateTime nacimiento, string direccion)
        {

            this.alumnoId = alumnoId;
            this.nombre_a = nombre;
            this.apellido_a = apellido;
            this.dni_a = dni;
            this.telefono_a = telefono;
            this.pais_a = pais;
            this.promedio_a = null;
            this.localidad_a = localidad;
            this.provincia_a = provincia;
            this.pais_a = pais;
            this.edad_a = edad;
            this.genero_a = genero;
            this.fechaNacimiento_a = nacimiento;
            this.direccion_a = direccion;
        }
    }
}
