//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class connectAll
    {
        public int connectAllId { get; set; }
        public Nullable<int> alumnoId_1 { get; set; }
        public Nullable<int> cursoMateriaId_1 { get; set; }
        public Nullable<int> aulaId_1 { get; set; }
        public Nullable<double> parcial_1 { get; set; }
        public Nullable<double> parcial_2 { get; set; }
        public Nullable<double> parcial_3 { get; set; }
        public Nullable<double> notaFinal { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual aula aula { get; set; }
        public virtual cursoMateria cursoMateria { get; set; }

        public connectAll() { }

        public connectAll(int connectAllId, int alumnoId, int cursoMateriaId, int aulaId)
        {
            this.alumnoId_1 = alumnoId;
            this.connectAllId = connectAllId;
            this.cursoMateriaId_1 = cursoMateriaId;
            this.aulaId_1 = aulaId;
            this.parcial_1 = 1;
            this.parcial_2 = 1;
            this.parcial_3 = 1;
            this.notaFinal = 1;
        }
    }
}
