//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursoMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cursoMateria()
        {
            this.connectAll = new HashSet<connectAll>();
        }
    
        public int cursoMateriaId { get; set; }
        public Nullable<int> materiaId_1 { get; set; }
        public Nullable<int> cursoId_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connectAll> connectAll { get; set; }
        public virtual curso curso { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
