//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor()
        {
            this.ProfesorMateria = new HashSet<ProfesorMateria>();
        }
    
        public int profesorId { get; set; }
        public string nombre_p { get; set; }
        public string apellido_p { get; set; }
        public string dni_p { get; set; }
        public string telefono_p { get; set; }
        public Nullable<System.DateTime> fechaNacimiento_p { get; set; }
        public Nullable<int> edad_p { get; set; }
        public string direccion_p { get; set; }
        public string pais_p { get; set; }
        public string provincia_p { get; set; }
        public string localidad_p { get; set; }
        public string genero_p { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesorMateria> ProfesorMateria { get; set; }
        public profesor(int profesorId, string nombre, string apellido, string dni, string telefono, int edad,
    string direccion, string pais, string provincia, string localidad, DateTime nacimiento, string genero)
        {
            this.profesorId = profesorId;
            this.nombre_p = nombre;
            this.apellido_p = apellido;
            this.dni_p = dni;
            this.telefono_p = telefono;
            this.fechaNacimiento_p = nacimiento;
            this.edad_p = edad;
            this.direccion_p = direccion;
            this.pais_p = pais;
            this.provincia_p = provincia;
            this.localidad_p = localidad;
            this.genero_p = genero;
        }
    }
}
