//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorMateria
    {
        public int profesorMateriaId { get; set; }
        public Nullable<int> profesorId_1 { get; set; }
        public Nullable<int> materiaId_2 { get; set; }
        public string turno { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual profesor profesor { get; set; }

        public ProfesorMateria() { }
        public ProfesorMateria(int id, int profesorId, int materiaId, string turno)
        {
            this.profesorMateriaId = id;
            this.profesorId_1 = profesorId;
            this.materiaId_2 = materiaId;
            this.turno = turno;
        }
    }
}
