//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entitys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversidadEntitiesSql : DbContext
    {
        public UniversidadEntitiesSql()
            : base("name=UniversidadEntitiesSql")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<aula> aula { get; set; }
        public virtual DbSet<connectAll> connectAll { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<cursoMateria> cursoMateria { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<ProfesorMateria> ProfesorMateria { get; set; }
    }
}
